apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aws-node-termination-handler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- if .Values.enableSqsTerminationDraining }}
    {{- include "aws-node-termination-handler.labelsDeployment" . | nindent 4 }}
  {{- else }}
    {{- include "aws-node-termination-handler.labelsDaemonset" . | nindent 4 }}
  {{- end }}
spec:
  egress:
  - {}
  ingress:
  - {}
  podSelector:
    matchLabels:
    {{- if .Values.enableSqsTerminationDraining }}
      {{- include "aws-node-termination-handler.selectorLabelsDeployment" . | nindent 6 }}
    {{- else }}
      {{- include "aws-node-termination-handler.selectorLabelsDaemonset" . | nindent 6 }}
    {{- end }}
  policyTypes:
  - Egress
  - Ingress
status: {}
