{{- if .Values.enableSqsTerminationDraining }}
{{ if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "aws-node-termination-handler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-node-termination-handler.labels" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: aws-node-termination-handler
      controlledValues: RequestsAndLimits
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ include "aws-node-termination-handler.fullname" . }}
  updatePolicy:
    updateMode: Auto
{{ end }}
{{ end }}
