apiVersion: v1
appVersion: 1.22.1
description: Deploy components for the aws-node-termination-handler app
name: aws-node-termination-handler
version: 0.0.0
home: https://github.com/giantswarm/aws-node-termination-handler-app
icon: https://s.giantswarm.io/app-icons/aws/2/light.svg
sources:
  - https://raw.githubusercontent.com/giantswarm/aws-node-termination-handler-app/v[[ .Version ]]/README.md
restrictions:
  compatibleProviders: ["aws"]
annotations:
  application.giantswarm.io/team: "phoenix"
