{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "aws-node-termination-handler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-node-termination-handler.labels" . | nindent 4 }}
  annotations:
    {{- include "giantswarm.irsa.annotation" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
