apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-node-termination-handler-bundle.clusterID" . }}-aws-node-termination-handler-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-node-termination-handler-bundle.labels" . | nindent 4 }}
data:
  values: |
  {{- (include "giantswarm.workloadValues" .) | nindent 4 }}
